# SQLite version 3.x
#   gem install sqlite3
development:
  adapter: mysql
  database: spree_development
  username: root
  password:

test:
  adapter: mysql
  database: spree_test
  username: root
  password: 

production:
  adapter: mysql
  database: spree_development
  username: root
  password: 
